version: '3'

networks:
  default: ~

services:
  app:
    build: ./doc
    volumes:
      - ./:/var/www/html
      - ./config/db:/db
    networks:
      - default

  redis:
    image: "redis"
    expose:
      - 6379
    networks:
      - default
