version: '3.7'

services:
  bdt.db:
    build: ./docker/mysql
    image: bdt/db
    restart: on-failure
    expose:
      - 3306
    env_file: .env
    volumes:
      - ./var/mysql:/var/lib/mysql
      - ./docker/mysql/add_databases.sh:/docker-entrypoint-initdb.d/add_databases.sh

  bdt.back:
    build:
      context: .
      dockerfile: docker/back/Dockerfile
      args:
        COMPOSER_SHA384: "${COMPOSER_SHA384}"
    restart: on-failure
    env_file: .env
    user: "${BACKEND_USER}"
    ports:
      - 9000:9000
    volumes:
      - ./apps/back/:/usr/src/app
    depends_on:
      - bdt.db

  bdt.nginx:
    image: nginx:1.15.3-alpine
    restart: on-failure
    volumes:
      - ./apps/back/web/:/usr/src/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT}:80"
    env_file: .env
    depends_on:
      - bdt.back

  bdt.front:
    build:
      context: .
      dockerfile: docker/front/Dockerfile
    restart: on-failure
    env_file: .env
    ports:
      - "${FRONT_PORT}:3000"
    volumes:
      - ./apps/front/:/usr/src/app
#    depends_on:
#      - bdt.nginx
  bdt.redis:
    build: ./docker/redis
    image: bdt/redis
    expose:
      - 6379
